name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          architecture: 'x64'

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      # Run Pytest tests
      - name: Run tests
        run: |
         poetry run pytest