name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          architecture: 'x64'

      # Install dependencies
      - name: Install Dependencies
        run: |
          echo "Installing Backend Dependencies"
          python -m pip install --upgrade pip
          pip install poetry coverage
          poetry install

      # Run Pytest tests
      - name: Run Tests
        run: |
          echo "Running Comp Blocks Tests"
          export VERBOSE=1
          poetry run coverage run -m pytest src/
          poetry run coverage report -m